language: python
python:
  - "3.5"

cache: pip
# command to install dependencies
install:
  - pip install -r requirements.txt

before script:
  - psql -c "CREATE DATABASE store_manager_test;"-U postgres
  - psql -c "CREATE USER postgres;" -U postgres
  - psql -c "ALTER USER postgres WITH password 'manu2012';" -U postgres
# command to run tests
script:
  - pytest --cov-report term-missing --cov=app

after_success:
  - coveralls
