language: python
python:
  - "3.5"

cache: pip

services:
  - postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create database store_manager_test;" -U postgres

script:
  - export APP_SETTINGS='testing'
  - export SECRET_KEY='Imnottellingyou'
  - export DATABASE_URL='postgresql://postgres:manu2012@localhost:5432/store_manager_test'
  - pytest --cov-report term-missing --cov=app

after_success:
  - coveralls
